In [1]:
import pandas as pd
from datasets import load_dataset

# Loading Data
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset["train"].to_pandas()

# Data Cleanup
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.describe()

                  job_posted_date  salary_year_avg  salary_hour_avg
count                      785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860247    123286.274072        47.016598
min           2023-01-01 00:00:04     15000.000000         8.000000
25%           2023-03-20 10:05:48     90000.000000        27.500000
50%           2023-06-29 06:11:38    115000.000000        45.980000
75%           2023-09-27 01:01:16    150000.000000        61.159996
max           2023-12-31 23:59:58    960000.000000       391.000000
std                           NaN     48312.449482        21.890738

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

In [4]:
df.count()

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
dtype: int64

In [5]:
df["salary_year_avg"].mean()

np.float64(123286.27407182401)

In [6]:
df["salary_year_avg"].min

<bound method Series.min of 0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
785736   NaN
785737   NaN
785738   NaN
785739   NaN
785740   NaN
Name: salary_year_avg, Length: 785741, dtype: float64>

In [7]:
min_salary = df["salary_year_avg"].idxmin()
print(min_salary)

665729

In [8]:
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [9]:
df["job_title_short"].unique()

<ArrowStringArray>
[     'Senior Data Engineer',              'Data Analyst',
             'Data Engineer',          'Business Analyst',
            'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst',            'Cloud Engineer',
     'Senior Data Scientist',         'Software Engineer']
Length: 10, dtype: str

In [10]:
df["job_title_short"].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [11]:
df.groupby("job_title_short")["salary_year_avg"].min()

job_title_short
Business Analyst             16500.0
Cloud Engineer               42000.0
Data Analyst                 25000.0
Data Engineer                15000.0
Data Scientist               27000.0
Machine Learning Engineer    30000.0
Senior Data Analyst          30000.0
Senior Data Engineer         35000.0
Senior Data Scientist        45000.0
Software Engineer            28000.0
Name: salary_year_avg, dtype: float64

In [12]:
df.groupby("job_title_short")["salary_year_avg"].median()

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

In [13]:
df.groupby("job_title_short")[["salary_year_avg", "salary_hour_avg"]].median()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                   85000.0        40.362499
Cloud Engineer                     90000.0        40.000000
Data Analyst                       90000.0        32.615002
Data Engineer                     125000.0        58.500000
Data Scientist                    127500.0        47.500000
Machine Learning Engineer         106415.0        47.535000
Senior Data Analyst               111175.0        47.500000
Senior Data Engineer              147500.0        61.500000
Senior Data Scientist             155500.0        47.620003
Software Engineer                  99150.0        47.560001

In [14]:
df.groupby("job_title_short")["salary_year_avg"].agg(["min", "max", "mean"])

                               min       max           mean
job_title_short
Business Analyst           16500.0  387460.0   91082.612833
Cloud Engineer             42000.0  280000.0  111268.453846
Data Analyst               25000.0  650000.0   93841.907854
Data Engineer              15000.0  525000.0  130125.604250
Data Scientist             27000.0  960000.0  135988.837171
Machine Learning Engineer  30000.0  325000.0  126774.315972
Senior Data Analyst        30000.0  425000.0  113911.363665
Senior Data Engineer       35000.0  425000.0  145840.611624
Senior Data Scientist      45000.0  890000.0  154206.292996
Software Engineer          28000.0  375000.0  113393.760054

In [15]:
df["job_country"].value_counts().head(20)

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Spain              25100
Singapore          23696
Sudan              21781
Netherlands        20631
Italy              17013
Canada             16029
Mexico             15139
Poland             14793
Portugal           14508
Australia          12955
South Africa       12414
Belgium            12078
Philippines        11786
Ireland            11162
Switzerland         9924
Name: count, dtype: int64

In [16]:
df["job_country"].isin(["Brazil"])

0         False
1         False
2         False
3         False
4         False
          ...
785736    False
785737    False
785738    False
785739    False
785740    False
Name: job_country, Length: 785741, dtype: bool

In [17]:
df["job_country"].isin(["Brazil"]).any()

np.True_

In [18]:
df["job_country"].isin(["North Korea"]).any()

np.False_

In [57]:
us_jobs = df[df["job_country"] == "United States"]
print(us_jobs)

             job_title_short  \
0       Senior Data Engineer
3              Data Engineer
5              Data Engineer
6       Senior Data Engineer
9             Data Scientist
...                      ...
785673        Data Scientist
785685          Data Analyst
785692        Data Scientist
785703          Data Analyst
785705          Data Analyst

                                                job_title      job_location  \
0       Senior Clinical Data Engineer / Principal Clin...     Watertown, CT
3       LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...   San Antonio, TX
5                                       GCP Data Engineer          Anywhere
6                       Senior Data Engineer  - GCP Cloud      Dearborn, MI
9                                       Data Scientist II          Anywhere
...                                                   ...               ...
785673                    Asset Management Data Scientist      New York, NY
785685                                       Data Analyst  Indianapolis, IN
785692               Data Scientist- Hybrid Work Location        Dayton, OH
785703            Data Analyst - CRYPTOGRAPHY - Full-time          Anywhere
785705          Expert Business Data Analyst - Now Hiring       Oakland, CA

                  job_via         job_schedule_type  job_work_from_home  \
0         via Work Nearby                 Full-time               False
3       via Diversity.com                 Full-time               False
5        via ZipRecruiter  Contractor and Temp work                True
6            via LinkedIn                 Full-time               False
9        via ZipRecruiter                 Full-time                True
...                   ...                       ...                 ...
785673    via Trabajo.org                 Full-time               False
785685    via Trabajo.org                 Full-time               False
785692    via Ai-Jobs.net                 Full-time               False
785703       via Snagajob                 Full-time                True
785705       via Snagajob                 Full-time               False

                  search_location     job_posted_date  job_no_degree_mention  \
0            Texas, United States 2023-06-16 13:44:15                  False
3            Texas, United States 2023-07-04 13:01:41                   True
5                         Georgia 2023-11-07 14:01:59                  False
6          Florida, United States 2023-03-27 13:18:18                  False
9         New York, United States 2023-04-23 13:02:57                  False
...                           ...                 ...                    ...
785673    New York, United States 2023-10-16 06:01:53                   True
785685    Illinois, United States 2023-07-16 06:01:27                   True
785692    Illinois, United States 2023-04-21 06:02:31                  False
785703       Texas, United States 2023-01-28 06:02:55                   True
785705  California, United States 2023-01-09 06:00:25                  False

        job_health_insurance    job_country salary_rate  salary_year_avg  \
0                      False  United States         NaN              NaN
3                      False  United States         NaN              NaN
5                      False  United States         NaN              NaN
6                      False  United States         NaN              NaN
9                      False  United States         NaN              NaN
...                      ...            ...         ...              ...
785673                 False  United States         NaN              NaN
785685                 False  United States         NaN              NaN
785692                  True  United States        year         157500.0
785703                 False  United States         NaN              NaN
785705                 False  United States         NaN              NaN

        salary_hour_avg                   company_name  \
0                   NaN           Boehringer Ingelheim
3                   NaN   Southwest Research Institute
5                   NaN                smart folks inc
6                   NaN  Miracle Software Systems, Inc
9                   NaN     Radwell International, LLC
...                 ...                            ...
785673              NaN           JPMorgan Chase & Co.
785685              NaN         Aara Technologies, Inc
785692              NaN                         Tenet3
785703              NaN    Axelon Services Corporation
785705              NaN               PG&E Corporation

                                               job_skills  \
0                                                     NaN
3       ['python', 'c++', 'java', 'matlab', 'aws', 'te...
5                                ['python', 'sql', 'gcp']
6       ['sql', 'python', 'java', 'sql server', 'gcp',...
9       ['sql', 'python', 'r', 'mongodb', 'mongodb', '...
...                                                   ...
785673                                                NaN
785685                                   ['sql', 'excel']
785692                          ['python', 'matlab', 'r']
785703                                                NaN
785705                       ['sql', 'python', 'tableau']

                                          job_type_skills
0                                                     NaN
3       {'cloud': ['aws'], 'libraries': ['tensorflow',...
5       {'cloud': ['gcp'], 'programming': ['python', '...
6       {'cloud': ['gcp', 'bigquery'], 'databases': ['...
9       {'analyst_tools': ['excel'], 'cloud': ['azure'...
...                                                   ...
785673                                                NaN
785685  {'analyst_tools': ['excel'], 'programming': ['...
785692         {'programming': ['python', 'matlab', 'r']}
785703                                                NaN
785705  {'analyst_tools': ['tableau'], 'programming': ...

[206292 rows x 17 columns]

In [26]:
us_jobs = us_jobs[us_jobs["salary_year_avg"].notna()]
print(us_jobs)

       job_title_short                                          job_title  \
92       Data Engineer            Remote - Data Engineer - Permanent - W2
100     Data Scientist            Data Scientist, Risk Data Mining - USDS
109       Data Analyst              Senior Supply Chain Analytics Analyst
116     Data Scientist                                     Data Scientist
146      Data Engineer  Data Engineer Graduate (Real Time Communicatio...
...                ...                                                ...
785563  Data Scientist  Data Scientist I/II (Model Risk Management & M...
785624   Data Engineer                   Data Analytics Engineer (Hybrid)
785641   Data Engineer                                      Data Engineer
785648  Data Scientist  Director Data Scientist - Commercial Platforms...
785692  Data Scientist               Data Scientist- Hybrid Work Location

             job_location                                    job_via  \
92               Anywhere                               via LinkedIn
100     Mountain View, CA                               via LinkedIn
109              Anywhere                                 via Get.It
116              Anywhere                               via LinkedIn
146           Seattle, WA                               via LinkedIn
...                   ...                                        ...
785563      Pensacola, FL  via Navy Federal Credit Union - Talentify
785624    Mt Prospect, IL                            via Ai-Jobs.net
785641       New York, NY                                   via Dice
785648  Pleasant Hill, CA                            via Ai-Jobs.net
785692         Dayton, OH                            via Ai-Jobs.net

       job_schedule_type  job_work_from_home            search_location  \
92             Full-time                True    Illinois, United States
100            Full-time               False  California, United States
109            Full-time                True    Illinois, United States
116            Full-time                True       Texas, United States
146            Full-time               False  California, United States
...                  ...                 ...                        ...
785563         Full-time               False     Florida, United States
785624         Full-time               False    Illinois, United States
785641         Full-time               False                    Georgia
785648         Full-time               False  California, United States
785692         Full-time               False    Illinois, United States

           job_posted_date  job_no_degree_mention  job_health_insurance  \
92     2023-02-21 13:29:59                  False                  True
100    2023-07-31 13:01:18                  False                  True
109    2023-10-12 13:02:19                  False                  True
116    2023-10-04 13:04:23                  False                 False
146    2023-10-21 13:06:16                  False                  True
...                    ...                    ...                   ...
785563 2023-01-11 06:22:10                  False                 False
785624 2023-08-31 06:02:16                  False                  True
785641 2023-01-04 16:36:07                   True                 False
785648 2023-04-12 06:02:51                  False                  True
785692 2023-04-21 06:02:31                  False                  True

          job_country salary_rate  salary_year_avg  salary_hour_avg  \
92      United States        year         120000.0              NaN
100     United States        year         228222.0              NaN
109     United States        year          89000.0              NaN
116     United States        year         114000.0              NaN
146     United States        year         129500.0              NaN
...               ...         ...              ...              ...
785563  United States        year         136400.0              NaN
785624  United States        year         139216.0              NaN
785641  United States        year         150000.0              NaN
785648  United States        year         221875.0              NaN
785692  United States        year         157500.0              NaN

                           company_name  \
92                         Apex Systems
100                              TikTok
109     Get It Recruit - Transportation
116                  4 Corner Resources
146                           ByteDance
...                                 ...
785563        Navy Federal Credit Union
785624                      Bosch Group
785641            Engage Partners, Inc.
785648                           84.51°
785692                           Tenet3

                                               job_skills  \
92                                      ['sql', 'python']
100                     ['sql', 'r', 'python', 'express']
109                 ['python', 'r', 'alteryx', 'tableau']
116     ['r', 'python', 'sql', 't-sql', 'hadoop', 'spa...
146     ['golang', 'scala', 'python', 'java', 'hadoop'...
...                                                   ...
785563  ['r', 'python', 'matplotlib', 'ggplot2', 'spar...
785624  ['go', 'python', 'r', 'sql', 'oracle', 'window...
785641                                                NaN
785648          ['python', 'azure', 'snowflake', 'spark']
785692                          ['python', 'matlab', 'r']

                                          job_type_skills
92                     {'programming': ['sql', 'python']}
100     {'programming': ['sql', 'r', 'python'], 'webfr...
109     {'analyst_tools': ['alteryx', 'tableau'], 'pro...
116     {'analyst_tools': ['tableau'], 'libraries': ['...
146     {'libraries': ['hadoop', 'spark'], 'programmin...
...                                                   ...
785563  {'analyst_tools': ['word', 'power bi', 'tablea...
785624  {'analyst_tools': ['alteryx', 'power bi', 'tab...
785641                                                NaN
785648  {'cloud': ['azure', 'snowflake'], 'libraries':...
785692         {'programming': ['python', 'matlab', 'r']}

[15766 rows x 17 columns]

In [55]:
# Somehow the formatting doesn't work, need to look into that
final_us_jobs = us_jobs.groupby("job_title_short")["salary_year_avg"].agg(["min", "max", "mean"]).sort_values("mean", ascending=False)
print(final_us_jobs)

                               min       max           mean
job_title_short
Senior Data Scientist      55000.0  475000.0  159330.432029
Machine Learning Engineer  44408.5  315000.0  154240.382812
Senior Data Engineer       45000.0  375000.0  151448.023186
Data Scientist             30000.0  960000.0  139946.707204
Software Engineer          48982.0  375000.0  137964.929588
Data Engineer              23496.0  525000.0  134226.676753
Cloud Engineer             42000.0  221844.0  120090.900000
Senior Data Analyst        35360.0  425000.0  115729.129954
Business Analyst           35000.0  387460.0   96175.447397
Data Analyst               25000.0  375000.0   94553.964924