In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  # we will use this for plotting

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.loc[:10, "salary_rate":"salary_hour_avg"]

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN              NaN              NaN
1          NaN              NaN              NaN
2          NaN              NaN              NaN
3          NaN              NaN              NaN
4          NaN              NaN              NaN
5          NaN              NaN              NaN
6          NaN              NaN              NaN
7          NaN              NaN              NaN
8          NaN              NaN              NaN
9          NaN              NaN              NaN
10         NaN              NaN              NaN

In [7]:
median_salary_year = df["salary_year_avg"].median()

In [6]:
median_salary_hour = df["salary_hour_avg"].median()

In [15]:
df_filled = df

df_filled["salary_year_avg"] = df_filled["salary_year_avg"].fillna(median_salary_year)
df_filled["salary_hour_avg"] = df_filled["salary_hour_avg"].fillna(median_salary_hour)

In [19]:
df_filled.loc[:10, "salary_year_avg":"salary_hour_avg"]

    salary_year_avg  salary_hour_avg
0          115000.0         115000.0
1          115000.0         115000.0
2          115000.0         115000.0
3          115000.0         115000.0
4          115000.0         115000.0
5          115000.0         115000.0
6          115000.0         115000.0
7          115000.0         115000.0
8          115000.0         115000.0
9          115000.0         115000.0
10         115000.0         115000.0

In [20]:
df_unique = df_filled

df_unique = df_unique.drop_duplicates()

print("Length of original df:           ", len(df_filled))
print("Length of drop duplicates df:    ", len(df_unique))
print("Rows dropped:                    ", len(df_filled) - len(df_unique))

Length of original df:            785741
Length of drop duplicates df:     785640
Rows dropped:                     101

In [21]:
df_unique = df_unique.drop_duplicates(subset=["job_title", "company_name"])

print("Length of original df:           ", len(df_filled))
print("Length of drop duplicates df:    ", len(df_unique))
print("Rows dropped:                    ", len(df_filled) - len(df_unique))

Length of original df:            785741
Length of drop duplicates df:     508042
Rows dropped:                     277699

In [23]:
df_unique.loc[:10]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,115000.0,115000.0,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,115000.0,115000.0,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,115000.0,115000.0,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,115000.0,115000.0,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,115000.0,115000.0,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,115000.0,115000.0,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,115000.0,115000.0,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,NaN,115000.0,115000.0,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,NaN,115000.0,115000.0,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,115000.0,115000.0,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
10,Data Engineer,Erfahrene*r Data Engineer*in (m/w/d),"Basel, Switzerland",via LinkedIn,Full-time,False,Switzerland,2023-04-17 13:27:32,True,False,Switzerland,NaN,115000.0,115000.0,ROCKEN®,"['python', 'databricks', 'azure', 'spark']","{'cloud': ['databricks', 'azure'], 'libraries'..."