In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

# DataFrame Copy
df_original = df.copy()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.sample()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
508150,Data Analyst,BI Data Warehouse Analyst,"Chicago, IL",via LinkedIn,Full-time,False,"Illinois, United States",2023-06-27 11:02:34,False,False,United States,NaN,NaN,NaN,Kemper,"['sql', 'oracle', 'snowflake', 'jira']","{'async': ['jira'], 'cloud': ['oracle', 'snowf..."

In [3]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
766661,Senior Data Scientist,Senior Data Scientist,"Oakhurst, CA",via BeBee,Full-time,False,"California, United States",2023-09-12 01:03:14,False,False,United States,NaN,NaN,NaN,Resource Logistics,"['python', 'pandas', 'nltk', 'tableau', 'micro...","{'analyst_tools': ['tableau', 'microstrategy',..."
257338,Software Engineer,Iga IT Governance Analyst,"Doha, Qatar",via BeBee دولة قطر,Full-time,False,Qatar,2023-12-16 07:28:42,False,False,Qatar,NaN,NaN,NaN,Brunel,NaN,NaN
320062,Senior Data Scientist,Senior Data Scientist,"Oxfordshire, UK",via WTRF Jobs,Full-time,False,United Kingdom,2023-05-31 17:19:17,False,False,United Kingdom,NaN,NaN,NaN,In Technology Group,"['python', 'r']","{'programming': ['python', 'r']}"
470640,Data Analyst,Research Data and Laboratory Analyst,"Fort Lauderdale, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-11-22 14:02:39,False,False,United States,NaN,NaN,NaN,Ascendo Resources,"['unix', 'excel', 'spreadsheet']","{'analyst_tools': ['excel', 'spreadsheet'], 'o..."
689905,Data Analyst,Data and Statistical Analyst/Researcher,Dubai - United Arab Emirates,via Indeed,Full-time,False,United Arab Emirates,2023-04-04 10:45:39,False,False,United Arab Emirates,NaN,NaN,NaN,KCORP,"['python', 'spss', 'excel', 'word', 'powerpoin...","{'analyst_tools': ['spss', 'excel', 'word', 'p..."
629452,Senior Data Engineer,Senior Data Engineer,"Vilnius, Vilnius City Municipality, Lithuania",via LinkedIn,Full-time,False,Lithuania,2023-10-22 12:34:31,True,False,Lithuania,NaN,NaN,NaN,Railsr,"['c', 'java', 'c#', 'python', 'aws', 'azure', ...","{'cloud': ['aws', 'azure', 'gcp', 'databricks'..."
684938,Data Analyst,"Data Analyst, Medical Devices",Argentina,"via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Argentina,2023-10-07 10:40:09,False,False,Argentina,NaN,NaN,NaN,"International Consulting Associates, Inc.",NaN,NaN
49633,Data Scientist,Data Labeling Expert,"Ho Chi Minh City, Vietnam",via Trabajo.org,Full-time,False,Vietnam,2023-11-01 06:29:41,False,False,Vietnam,NaN,NaN,NaN,CODE LEAP,NaN,NaN
600764,Data Scientist,Data Scientist,"Warsaw, Poland",via LinkedIn,Full-time,False,Poland,2023-10-17 09:23:15,False,False,Poland,NaN,NaN,NaN,mBank S.A.,"['python', 'sql', 'spark', 'hadoop', 'power bi']","{'analyst_tools': ['power bi'], 'libraries': [..."
52393,Data Analyst,Data Analyst,Philippines,via Trabajo.org,Full-time,False,Philippines,2023-12-23 06:35:08,True,False,Philippines,NaN,NaN,NaN,Collabera Technologies Private Limited Inc.,"['python', 'sql', 'excel', 'power bi']","{'analyst_tools': ['excel', 'power bi'], 'prog..."

In [4]:
df.sample(10, random_state=42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,NaN,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,NaN,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}
183426,Data Analyst,Data Analyst,Singapore,via Singapore | JobsDB,Full-time,False,Singapore,2023-11-09 16:07:57,False,False,Singapore,NaN,NaN,NaN,FLEXOSENSE PTE. LTD.,"['r', 'python', 'java', 'sql', 'sql server', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
287790,Data Analyst,Data Analyst,"Tampa, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-07-14 17:02:23,True,False,United States,NaN,NaN,NaN,Iris Software Inc.,"['sql', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
541983,Data Analyst,"Data Analyst, Cloud Systems Jobs","Chantilly, VA",via Clearance Jobs,Full-time,False,Georgia,2023-06-15 19:44:34,False,False,United States,NaN,NaN,NaN,SAIC,"['sql', 'r', 'matlab', 'python', 'oracle', 'aw...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
416896,Data Scientist,Alternant Actuariat & Data Science H/F,France,via LinkedIn,Full-time,False,France,2023-09-22 16:47:24,False,False,France,NaN,NaN,NaN,KPMG France,NaN,NaN
780907,Data Engineer,"Data Engineer with Fivetran,Qlik Must","Mexico City, CDMX, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-16 06:19:09,False,False,Mexico,NaN,NaN,NaN,CORUS Consulting,"['oracle', 'snowflake', 'aws', 'azure', 'alter...","{'analyst_tools': ['alteryx'], 'cloud': ['orac..."

In [6]:
# Id you use copy() method, it will have a different id. If you use df = df_altered, it will have the same id
# So its better to use copy() method
df_altered = df_original
df_altered.loc[:5, "salary_year_avg"]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [7]:
# Calculating the median salary
median_salary = df_altered['salary_year_avg'].median()

# Filling the missing values with the median salary
df_altered['salary_year_avg'] = df_altered.loc[:,'salary_year_avg'].fillna(median_salary)

In [8]:
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

In [9]:
df_altered.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [10]:
df_original.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [11]:
print('ID of df_original:               ', id(df_original))
print('ID of df_altered:                ', id(df_altered))
print('Are the two dataframes the same? ', id(df_original) == id(df_altered))

ID of df_original:                14207404624
ID of df_altered:                 14207404624
Are the two dataframes the same?  True

In [12]:
f_original = df.copy()
df_altered = df_original.copy()

print('ID of df_original:               ', id(df_original))
print('ID of df_altered:                ', id(df_altered))
print('Are the two dataframes the same? ', id(df_original) == id(df_altered))

ID of df_original:                14207404624
ID of df_altered:                 14205028624
Are the two dataframes the same?  False

In [13]:
# Calculating the median salary
median_salary = df_altered['salary_year_avg'].median()

# Filling the missing values with the median salary
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [15]:
# This is wrong, check it why
df_original.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64